#!/bin/bash

set -e
set -x

AWS_ACCOUNT='847437976396'
REGION='us-west-2'
REGISTRY="${AWS_ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com"
REPOSITORY='teg-ci'
TAG='ci' # change this if you have pushed an image with a new tag
IMAGE="${REGISTRY}/${REPOSITORY}:${TAG}"

set
echo $PWD

REAL_CORES=`cat /proc/cpuinfo | grep "core id" | sort | uniq | wc -l`

# Pull image if we don't have a locally cached version
if ! docker images "$IMAGE" | grep --quiet "$IMAGE"; then
  eval $(aws --region "$REGION" ecr get-login)
  docker pull "$IMAGE"
fi

docker run --rm=true -e "PARALLEL_TEST_PROCESSORS=$REAL_CORES" -v $PWD:/source -v ~/.buildbox/be-bundle-cache:/cache -v /tmp/ramdisk:/tmp/ramdisk -t "$IMAGE" /source/script/docker_tests
